classes:
  - person
  - chair
  - laptop
  - monitor
  - cup
  - bottle
  - cell phone
  - backpack
  - keyboard
  - mouse
  - book
  - clock
  - tv
  - screen

aliases:
  tv: monitor
  tvmonitor: monitor
  screen: monitor
